---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotalservices/docker-concourse-cf-tools
    tag: latest

inputs:
  - name: git-repo
  - name: music-release
  - name: version

outputs:
  - name: app-manifest-output

run:
  path: git-repo/ci/tasks/app-manifest-prep.sh