---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: openjdk
    tag: 8-jdk

inputs:
  - name: git-repo

run:
  path: /bin/bash
  args:
    - git-repo/ci/tasks/unit-test.sh