---
resources:
- name: git-repo
  type: git
  source:
    uri: https://github.com/ssherwood/spring-music
    branch: master

jobs:
- name: hello-world-job
  public: true
  plan:
  - get: git-repo
  - task: task_print-hello-world
    file: git-repo/ci/tasks/hello-world.yml 